import React, { useState } from 'react';
import { Modal } from './Modal';
import { useSampleStore } from '../stores/sampleStore';
import { useMasterDataStore } from '../stores/masterDataStore';
import { useAuthStore } from '../stores/authStore';
import { Save, X } from 'lucide-react';

interface SampleModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const SampleModal: React.FC<SampleModalProps> = ({ isOpen, onClose }) => {
    const { registerSample } = useSampleStore();
    const { products } = useMasterDataStore();
    const { user } = useAuthStore();

    const [formData, setFormData] = useState({
        productId: '',
        batchNumber: '',
        lotNumber: '',
        manufacturingDate: '',
        expiryDate: '',
        quantity: 0,
        unit: 'g',
        priority: 'medium' as 'low' | 'medium' | 'high' | 'urgent',
        dueDate: '',
        assignedTo: '',
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        const selectedProduct = products.find(p => p.id === formData.productId);
        if (!selectedProduct) return;

        const newSample = {
            sampleNumber: '', // Will be generated by store
            productId: formData.productId,
            batchNumber: formData.batchNumber,
            lotNumber: formData.lotNumber,
            manufacturingDate: formData.manufacturingDate,
            expiryDate: formData.expiryDate,
            receivedDate: new Date().toISOString(),
            receivedBy: user ? `${user.firstName} ${user.lastName}` : 'System User',
            quantity: Number(formData.quantity),
            unit: formData.unit,
            testMethodIds: selectedProduct.specifications.map(s => s.testMethodId),
            customFields: {},
            priority: formData.priority,
            dueDate: formData.dueDate,
            assignedTo: formData.assignedTo,
        };

        registerSample(newSample);
        onClose();

        // Reset form
        setFormData({
            productId: '',
            batchNumber: '',
            lotNumber: '',
            manufacturingDate: '',
            expiryDate: '',
            quantity: 0,
            unit: 'g',
            priority: 'medium',
            dueDate: '',
            assignedTo: '',
        });
    };

    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Register New Sample" size="lg">
            <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid grid-cols-2 gap-6">
                    {/* Product Selection */}
                    <div className="col-span-2">
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Product *
                        </label>
                        <select
                            required
                            value={formData.productId}
                            onChange={(e) => setFormData({ ...formData, productId: e.target.value })}
                            className="input"
                        >
                            <option value="">Select Product</option>
                            {products.map(product => (
                                <option key={product.id} value={product.id}>
                                    {product.name} ({product.code})
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Batch Number */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Batch Number *
                        </label>
                        <input
                            type="text"
                            required
                            value={formData.batchNumber}
                            onChange={(e) => setFormData({ ...formData, batchNumber: e.target.value })}
                            className="input"
                            placeholder="e.g., BATCH-001"
                        />
                    </div>

                    {/* Lot Number */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Lot Number
                        </label>
                        <input
                            type="text"
                            value={formData.lotNumber}
                            onChange={(e) => setFormData({ ...formData, lotNumber: e.target.value })}
                            className="input"
                            placeholder="Optional"
                        />
                    </div>

                    {/* Manufacturing Date */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Manufacturing Date
                        </label>
                        <input
                            type="date"
                            value={formData.manufacturingDate}
                            onChange={(e) => setFormData({ ...formData, manufacturingDate: e.target.value })}
                            className="input"
                        />
                    </div>

                    {/* Expiry Date */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Expiry Date
                        </label>
                        <input
                            type="date"
                            value={formData.expiryDate}
                            onChange={(e) => setFormData({ ...formData, expiryDate: e.target.value })}
                            className="input"
                        />
                    </div>

                    {/* Quantity */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Quantity *
                        </label>
                        <div className="flex gap-2">
                            <input
                                type="number"
                                required
                                min="0"
                                step="0.01"
                                value={formData.quantity}
                                onChange={(e) => setFormData({ ...formData, quantity: parseFloat(e.target.value) })}
                                className="input flex-1"
                            />
                            <select
                                value={formData.unit}
                                onChange={(e) => setFormData({ ...formData, unit: e.target.value })}
                                className="input w-24"
                            >
                                <option value="g">g</option>
                                <option value="mg">mg</option>
                                <option value="ml">ml</option>
                                <option value="L">L</option>
                                <option value="pcs">pcs</option>
                            </select>
                        </div>
                    </div>

                    {/* Priority */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Priority *
                        </label>
                        <select
                            required
                            value={formData.priority}
                            onChange={(e) => setFormData({ ...formData, priority: e.target.value as any })}
                            className="input"
                        >
                            <option value="low">Low</option>
                            <option value="medium">Medium</option>
                            <option value="high">High</option>
                            <option value="urgent">Urgent</option>
                        </select>
                    </div>

                    {/* Due Date */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Due Date
                        </label>
                        <input
                            type="date"
                            value={formData.dueDate}
                            onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                            className="input"
                        />
                    </div>

                    {/* Assigned Analyst - Temporarily Disabled */}
                    {/* <div className="col-span-2">
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                            Assign Analyst (Optional)
                        </label>
                        <select
                            value={formData.assignedTo}
                            onChange={(e) => setFormData({ ...formData, assignedTo: e.target.value })}
                            className="input"
                        >
                            <option value="">Select Analyst</option>
                            {users.filter(u => u.role === 'analyst').map(analyst => (
                                <option key={analyst.id} value={analyst.id}>
                                    {analyst.firstName} {analyst.lastName}
                                </option>
                            ))}
                        </select>
                    </div> */}
                </div>

                {/* Actions */}
                <div className="flex justify-end gap-3 pt-4 border-t border-slate-200 dark:border-slate-700">
                    <button
                        type="button"
                        onClick={onClose}
                        className="btn btn-secondary flex items-center gap-2"
                    >
                        <X className="w-4 h-4" />
                        Cancel
                    </button>
                    <button
                        type="submit"
                        className="btn btn-primary flex items-center gap-2"
                    >
                        <Save className="w-4 h-4" />
                        Register Sample
                    </button>
                </div>
            </form>
        </Modal>
    );
};
