import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { useCompanyConfig } from '../stores/companyConfigStore';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: typeof autoTable;
        lastAutoTable: {
            finalY: number;
        };
    }
}

interface AnalyticsReportData {
    productName: string;
    testMethodName: string;
    historicalData: {
        batch: string;
        value: number;
        date: string;
    }[];
    specification: {
        spec: string;
        lsl?: number;
        usl?: number;
        target?: number;
        unit?: string;
    };
    controlLimits: {
        ucl: number;
        lcl: number;
        mean: number;
    } | null;
    cpkResult: {
        cpk: number;
        cp: number;
        cpkl: number;
        cpku: number;
        status: string;
        interpretation: string;
    } | null;
    trendResult: {
        trend: string;
        isOOS: boolean;
        isOOT: boolean;
        warnings: string[];
    } | null;
}

class AnalyticsReportGenerator {
    private doc: jsPDF;
    private pageWidth: number;
    private pageHeight: number;
    private margin: number = 15;
    private currentY: number = 15;

    constructor() {
        this.doc = new jsPDF();
        this.pageWidth = this.doc.internal.pageSize.getWidth();
        this.pageHeight = this.doc.internal.pageSize.getHeight();
    }

    private checkPageBreak(requiredSpace: number = 40): void {
        if (this.currentY + requiredSpace > this.pageHeight - 30) {
            this.doc.addPage();
            this.currentY = this.margin;
        }
    }

    private addHeader(title: string, subtitle: string, generatedBy: string) {
        const { config } = useCompanyConfig.getState();

        // Helper function to convert hex to RGB
        const hexToRgb = (hex: string): [number, number, number] => {
            const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            return result
                ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
                : [59, 130, 246]; // Default blue
        };

        const bgColor = hexToRgb(config.headerBackgroundColor);
        const textColor = hexToRgb(config.headerTextColor);

        // Company Header Section
        this.doc.setFillColor(...bgColor);
        this.doc.rect(0, 0, this.pageWidth, 35, 'F');

        // Logo
        if (config.logoFile) {
            try {
                this.doc.addImage(config.logoFile, 'PNG', this.margin, 5, 25, 25);
            } catch (e) {
                console.error('Failed to add logo', e);
            }
        }

        // Company Name
        this.doc.setTextColor(...textColor);
        this.doc.setFontSize(16);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(config.companyName, this.pageWidth / 2, 12, { align: 'center' });

        // Company Address
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(config.companyAddress, this.pageWidth / 2, 18, { align: 'center' });
        this.doc.text(`Phone: ${config.companyPhone} | Email: ${config.companyEmail}`, this.pageWidth / 2, 23, { align: 'center' });

        // Report Title
        this.currentY = 45;
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFontSize(18);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(title, this.pageWidth / 2, this.currentY, { align: 'center' });

        if (subtitle) {
            this.currentY += 7;
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'normal');
            this.doc.text(subtitle, this.pageWidth / 2, this.currentY, { align: 'center' });
        }

        // Document Info
        this.currentY += 10;
        this.doc.setFontSize(9);
        this.doc.text(`Generated By: ${generatedBy}`, this.pageWidth - this.margin, this.currentY, { align: 'right' });
        this.currentY += 5;
        this.doc.text(`Date: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`, this.pageWidth - this.margin, this.currentY, { align: 'right' });

        this.currentY += 10;
        this.doc.setDrawColor(200, 200, 200);
        this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
        this.currentY += 10;
    }

    private addFooter() {
        const { config } = useCompanyConfig.getState();
        const pageCount = this.doc.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);
            this.doc.setFontSize(8);
            this.doc.setTextColor(128, 128, 128);

            this.doc.text(
                `Page ${i} of ${pageCount}`,
                this.pageWidth / 2,
                this.pageHeight - 10,
                { align: 'center' }
            );

            this.doc.text(
                'CONFIDENTIAL - For Internal Use Only',
                this.margin,
                this.pageHeight - 10
            );

            this.doc.text(
                config.companyName,
                this.pageWidth - this.margin,
                this.pageHeight - 10,
                { align: 'right' }
            );
        }
    }

    generateReport(data: AnalyticsReportData, generatedBy: string): void {
        this.addHeader('Statistical Process Control Report', `${data.productName} - ${data.testMethodName}`, generatedBy);

        // 1. Specification & Control Limits Summary
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Specification & Control Limits', this.margin, this.currentY);
        this.currentY += 7;

        const specData = [
            ['Specification', data.specification.spec],
            ['Target', data.specification.target ? `${data.specification.target} ${data.specification.unit || ''}` : 'N/A'],
            ['LSL', data.specification.lsl ? `${data.specification.lsl} ${data.specification.unit || ''}` : 'N/A'],
            ['USL', data.specification.usl ? `${data.specification.usl} ${data.specification.unit || ''}` : 'N/A'],
        ];

        if (data.controlLimits) {
            specData.push(
                ['Mean', data.controlLimits.mean.toFixed(3)],
                ['LCL (-3σ)', data.controlLimits.lcl.toFixed(3)],
                ['UCL (+3σ)', data.controlLimits.ucl.toFixed(3)]
            );
        }

        autoTable(this.doc, {
            startY: this.currentY,
            body: specData,
            theme: 'plain',
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 10 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 60 },
                1: { cellWidth: 'auto' },
            },
        });

        this.currentY = this.doc.lastAutoTable.finalY + 15;

        // 2. Process Capability Analysis (CPK)
        if (data.cpkResult) {
            this.checkPageBreak();
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'bold');
            this.doc.text('Process Capability Analysis (CPK)', this.margin, this.currentY);
            this.currentY += 7;

            const cpkData = [
                ['CPK', data.cpkResult.cpk.toFixed(3)],
                ['CP', data.cpkResult.cp.toFixed(3)],
                ['CPK Lower', data.cpkResult.cpkl.toFixed(3)],
                ['CPK Upper', data.cpkResult.cpku.toFixed(3)],
                ['Status', data.cpkResult.status.toUpperCase()],
                ['Interpretation', data.cpkResult.interpretation],
            ];

            autoTable(this.doc, {
                startY: this.currentY,
                body: cpkData,
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] },
                margin: { left: this.margin, right: this.margin },
                styles: { fontSize: 10 },
                columnStyles: {
                    0: { fontStyle: 'bold', cellWidth: 60 },
                    1: { cellWidth: 'auto' },
                },
            });

            this.currentY = this.doc.lastAutoTable.finalY + 15;
        }

        // 3. Trend Analysis
        if (data.trendResult) {
            this.checkPageBreak();
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'bold');
            this.doc.text('Trend Analysis', this.margin, this.currentY);
            this.currentY += 7;

            const trendData = [
                ['Trend Direction', data.trendResult.trend.toUpperCase()],
                ['OOS Detected', data.trendResult.isOOS ? 'YES' : 'NO'],
                ['OOT Detected', data.trendResult.isOOT ? 'YES' : 'NO'],
            ];

            autoTable(this.doc, {
                startY: this.currentY,
                body: trendData,
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] },
                margin: { left: this.margin, right: this.margin },
                styles: { fontSize: 10 },
                columnStyles: {
                    0: { fontStyle: 'bold', cellWidth: 60 },
                    1: { cellWidth: 'auto' },
                },
            });

            this.currentY = this.doc.lastAutoTable.finalY + 10;

            if (data.trendResult.warnings.length > 0) {
                this.doc.setFontSize(10);
                this.doc.setFont('helvetica', 'bold');
                this.doc.setTextColor(220, 38, 38); // Red
                this.doc.text('Warnings:', this.margin, this.currentY);
                this.currentY += 5;
                this.doc.setFont('helvetica', 'normal');

                data.trendResult.warnings.forEach(warning => {
                    this.doc.text(`• ${warning}`, this.margin + 5, this.currentY);
                    this.currentY += 5;
                });

                this.doc.setTextColor(0, 0, 0); // Reset color
                this.currentY += 10;
            } else {
                this.currentY += 5;
            }
        }

        // 4. Historical Data Table
        this.checkPageBreak();
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Historical Data Points', this.margin, this.currentY);
        this.currentY += 7;

        const tableData = data.historicalData.map(item => [
            item.batch,
            item.date,
            item.value.toString()
        ]);

        autoTable(this.doc, {
            startY: this.currentY,
            head: [['Batch Number', 'Date', `Result (${data.specification.unit || ''})`]],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 9 },
        });

        this.addFooter();
    }

    save(filename: string): void {
        this.doc.save(filename);
    }
}

export const generateAnalyticsReport = (data: AnalyticsReportData, generatedBy: string): void => {
    const generator = new AnalyticsReportGenerator();
    generator.generateReport(data, generatedBy);
    generator.save(`SPC_Report_${format(new Date(), 'yyyyMMdd_HHmm')}.pdf`);
};

export default AnalyticsReportGenerator;
