import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { useCompanyConfig } from '../stores/companyConfigStore';
import type { Sample } from '../types';
import { useMasterDataStore } from '../stores/masterDataStore';
import { calculateCPK, analyzeTrend } from './statistics';

// Batch Analysis Report Generator
export const generateBatchAnalysisReport = (
    batchNumber: string,
    samples: Sample[],
    generatedBy: string
): void => {
    const doc = new jsPDF();
    const { config } = useCompanyConfig.getState();
    const { products, testMethods } = useMasterDataStore.getState();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 15;

    // Helper function to check page break
    const checkPageBreak = (requiredSpace: number = 40): void => {
        if (yPos + requiredSpace > pageHeight - 30) {
            doc.addPage();
            yPos = 15;
        }
    };

    // Company Header
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(config.companyName, pageWidth / 2, 12, { align: 'center' });
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(config.companyAddress, pageWidth / 2, 18, { align: 'center' });
    doc.text(`Phone: ${config.companyPhone} | Email: ${config.companyEmail}`, pageWidth / 2, 23, { align: 'center' });
    if (config.companyWebsite) {
        doc.text(config.companyWebsite, pageWidth / 2, 28, { align: 'center' });
    }

    // Report Title
    yPos = 45;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Batch Analysis Report', pageWidth / 2, yPos, { align: 'center' });
    yPos += 7;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Batch Number: ${batchNumber}`, pageWidth / 2, yPos, { align: 'center' });

    // Document Info
    yPos += 10;
    doc.setFontSize(9);
    const infoX = pageWidth - 15 - 60;
    doc.text(`Doc #: BATCH-${batchNumber}-${format(new Date(), 'yyyyMMdd')}`, infoX, yPos);
    yPos += 5;
    doc.text(`Generated By: ${generatedBy}`, infoX, yPos);
    yPos += 5;
    doc.text(`Date: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`, infoX, yPos);
    yPos += 10;

    // Separator
    doc.setDrawColor(200, 200, 200);
    doc.line(15, yPos, pageWidth - 15, yPos);
    yPos += 10;

    // Batch Summary
    const batchSamples = samples.filter(s => s.batchNumber === batchNumber);
    if (batchSamples.length === 0) {
        doc.setFontSize(12);
        doc.text('No samples found for this batch.', 15, yPos);
        doc.save(`Batch_Analysis_${batchNumber}_${format(new Date(), 'yyyyMMdd')}.pdf`);
        return;
    }

    const product = products.find(p => p.id === batchSamples[0].productId);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Batch Information', 15, yPos);
    yPos += 7;

    autoTable(doc, {
        startY: yPos,
        body: [
            ['Batch Number', batchNumber],
            ['Product', product?.name || 'Unknown'],
            ['Total Samples', batchSamples.length.toString()],
            ['Approved Samples', batchSamples.filter(s => s.status === 'approved').length.toString()],
            ['Date Range', `${format(new Date(Math.min(...batchSamples.map(s => new Date(s.receivedDate).getTime()))), 'yyyy-MM-dd')} to ${format(new Date(Math.max(...batchSamples.map(s => new Date(s.receivedDate).getTime()))), 'yyyy-MM-dd')}`],
        ],
        theme: 'plain',
        styles: { fontSize: 10 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 50 },
            1: { cellWidth: 'auto' },
        },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // Test Results Summary with Trending
    checkPageBreak();
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Test Results & Trend Analysis', 15, yPos);
    yPos += 7;

    // Group results by test method
    const testResultsMap = new Map<string, number[]>();
    batchSamples.forEach(sample => {
        sample.results.forEach(result => {
            if (result.status === 'approved' && result.results?.result) {
                const key = `${result.testMethodId}_${result.results.parameter}`;
                if (!testResultsMap.has(key)) {
                    testResultsMap.set(key, []);
                }
                testResultsMap.get(key)!.push(Number(result.results.result));
            }
        });
    });

    // Analyze each test
    const trendData: any[] = [];
    testResultsMap.forEach((values, key) => {
        const [testMethodId, parameter] = key.split('_');
        const testMethod = testMethods.find(tm => tm.id === testMethodId);
        const spec = product?.specifications.find(s => s.testMethodId === testMethodId && s.parameter === parameter);

        if (values.length >= 2 && spec) {
            const mean = values.reduce((a, b) => a + b, 0) / values.length;
            const stdDev = Math.sqrt(values.reduce((sq, n) => sq + Math.pow(n - mean, 2), 0) / values.length);

            let cpk = null;
            let trend = null;

            if (spec.lsl && spec.usl) {
                try {
                    cpk = calculateCPK(values, spec.lsl, spec.usl);
                } catch (e) {
                    console.error('CPK calculation error:', e);
                }
            }

            if (values.length >= 9 && spec.lsl && spec.usl) {
                try {
                    trend = analyzeTrend(values, spec.lsl, spec.usl);
                } catch (e) {
                    console.error('Trend analysis error:', e);
                }
            }

            trendData.push([
                testMethod?.name || 'Unknown',
                parameter,
                values.length.toString(),
                mean.toFixed(2),
                stdDev.toFixed(2),
                spec.spec,
                cpk ? cpk.cpk.toFixed(3) : 'N/A',
                trend ? trend.trend.toUpperCase() : 'N/A',
                trend && (trend.isOOS || trend.isOOT) ? '⚠ Alert' : '✓ OK'
            ]);
        }
    });

    if (trendData.length > 0) {
        autoTable(doc, {
            startY: yPos,
            head: [['Test Method', 'Parameter', 'n', 'Mean', 'Std Dev', 'Spec', 'CPK', 'Trend', 'Status']],
            body: trendData,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
            styles: { fontSize: 8 },
            columnStyles: {
                0: { cellWidth: 30 },
                1: { cellWidth: 25 },
                2: { cellWidth: 10 },
                3: { cellWidth: 18 },
                4: { cellWidth: 18 },
                5: { cellWidth: 25 },
                6: { cellWidth: 15 },
                7: { cellWidth: 18 },
                8: { cellWidth: 18 },
            },
        });

        yPos = (doc as any).lastAutoTable.finalY + 15;
    }

    // Individual Sample Results
    checkPageBreak();
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Individual Sample Results', 15, yPos);
    yPos += 7;

    batchSamples.forEach((sample, index) => {
        checkPageBreak(30);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`Sample ${index + 1}: ${sample.sampleNumber}`, 15, yPos);
        yPos += 5;

        if (sample.results && sample.results.length > 0) {
            const sampleResultData = sample.results.map(result => {
                const testMethod = testMethods.find(tm => tm.id === result.testMethodId);
                const spec = product?.specifications.find(s => s.testMethodId === result.testMethodId);

                return [
                    testMethod?.name || 'Unknown Test',
                    result.results?.result || 'Pending',
                    result.results?.unit || spec?.unit || '-',
                    spec?.spec || '-',
                    result.status.toUpperCase(),
                ];
            });

            autoTable(doc, {
                startY: yPos,
                head: [['Test', 'Result', 'Unit', 'Specification', 'Status']],
                body: sampleResultData,
                theme: 'grid',
                headStyles: { fillColor: [59, 130, 246], fontSize: 8 },
                styles: { fontSize: 8 },
                margin: { left: 20 },
            });

            yPos = (doc as any).lastAutoTable.finalY + 8;
        }
    });

    // Signature Section
    checkPageBreak(60);
    yPos += 10;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Approvals', 15, yPos);
    yPos += 10;

    const signatureWidth = 70;
    const signatureHeight = 25;

    // Prepared By
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Prepared By:', 15, yPos);
    doc.rect(15, yPos + 2, signatureWidth, signatureHeight);
    doc.setFontSize(8);
    doc.text('Signature: _____________________', 17, yPos + signatureHeight - 8);
    doc.text('Date: _____________', 17, yPos + signatureHeight - 2);

    // Approved By
    const approveX = 15 + signatureWidth + 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Approved By (QA Manager):', approveX, yPos);
    doc.rect(approveX, yPos + 2, signatureWidth, signatureHeight);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Signature: _____________________', approveX + 2, yPos + signatureHeight - 8);
    doc.text('Date: _____________', approveX + 2, yPos + signatureHeight - 2);

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        doc.text('CONFIDENTIAL - For Internal Use Only', 15, pageHeight - 10);
        doc.text(config.companyName, pageWidth - 15, pageHeight - 10, { align: 'right' });
    }

    doc.save(`Batch_Analysis_${batchNumber}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
