import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { Deviation, CAPA } from '../types/deviation';
import type { Sample } from '../types';
import { useCompanyConfig } from '../stores/companyConfigStore';
import { useMasterDataStore } from '../stores/masterDataStore';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: typeof autoTable;
    }
}

interface ReportHeader {
    title: string;
    subtitle?: string;
    documentNumber?: string;
    generatedBy: string;
    generatedAt: Date;
}

class ReportGenerator {
    private doc: jsPDF;
    private pageWidth: number;
    private pageHeight: number;
    private margin: number = 15;
    private currentY: number = 15;

    constructor() {
        this.doc = new jsPDF();
        this.pageWidth = this.doc.internal.pageSize.getWidth();
        this.pageHeight = this.doc.internal.pageSize.getHeight();
    }

    private hexToRgb(hex: string): [number, number, number] {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result
            ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
            : [59, 130, 246]; // Default blue
    }

    private addHeader(header: ReportHeader) {
        const { config } = useCompanyConfig.getState();

        const bgColor = this.hexToRgb(config.headerBackgroundColor);
        const textColor = this.hexToRgb(config.headerTextColor);

        // Header Background
        this.doc.setFillColor(...bgColor);
        this.doc.rect(0, 0, this.pageWidth, 35, 'F');

        // Company Logo
        if (config.logoFile) {
            try {
                this.doc.addImage(config.logoFile, 'PNG', this.margin, 5, 25, 25);
            } catch (e) {
                console.error('Failed to add logo to PDF', e);
            }
        }

        // Company Name and Details (centered in header)
        this.doc.setTextColor(...textColor);
        this.doc.setFontSize(14);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(config.companyName, this.pageWidth / 2, 12, { align: 'center' });

        this.doc.setFontSize(8);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(config.companyAddress, this.pageWidth / 2, 18, { align: 'center' });
        this.doc.text(`${config.companyPhone} | ${config.companyEmail}`, this.pageWidth / 2, 23, { align: 'center' });
        if (config.companyWebsite) {
            this.doc.text(config.companyWebsite, this.pageWidth / 2, 28, { align: 'center' });
        }

        // Report Title
        this.currentY = 45;
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFontSize(18);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(header.title, this.pageWidth / 2, this.currentY, { align: 'center' });

        if (header.subtitle) {
            this.currentY += 7;
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'normal');
            this.doc.text(header.subtitle, this.pageWidth / 2, this.currentY, { align: 'center' });
        }

        // Document Info Box
        this.currentY += 10;
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');

        const infoX = this.pageWidth - this.margin - 60;
        if (header.documentNumber) {
            this.doc.text(`Doc #: ${header.documentNumber}`, infoX, this.currentY);
            this.currentY += 5;
        }
        this.doc.text(`Generated By: ${header.generatedBy}`, infoX, this.currentY);
        this.currentY += 5;
        this.doc.text(`Date: ${format(header.generatedAt, 'yyyy-MM-dd HH:mm')}`, infoX, this.currentY);

        this.currentY += 10;

        // Separator line
        this.doc.setDrawColor(200, 200, 200);
        this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
        this.currentY += 10;
    }

    private addFooter() {
        const pageCount = this.doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);
            this.doc.setFontSize(8);
            this.doc.setTextColor(128, 128, 128);

            // Page number
            this.doc.text(
                `Page ${i} of ${pageCount}`,
                this.pageWidth / 2,
                this.pageHeight - 10,
                { align: 'center' }
            );

            // Confidential notice
            this.doc.text(
                'CONFIDENTIAL - For Internal Use Only',
                this.margin,
                this.pageHeight - 10
            );
        }
    }

    // Deviation Summary Report
    generateDeviationSummaryReport(
        deviations: Deviation[],
        generatedBy: string,
        filters?: { status?: string; severity?: string; dateRange?: { start: Date; end: Date } }
    ): void {
        const header: ReportHeader = {
            title: 'Deviation Summary Report',
            subtitle: filters ? this.getFilterDescription(filters) : undefined,
            documentNumber: `DEV-RPT-${format(new Date(), 'yyyyMMdd-HHmmss')}`,
            generatedBy,
            generatedAt: new Date(),
        };

        this.addHeader(header);

        // Summary Statistics
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Summary Statistics', this.margin, this.currentY);
        this.currentY += 7;

        const stats = this.calculateDeviationStats(deviations);

        autoTable(this.doc, {
            startY: this.currentY,
            head: [['Metric', 'Count', 'Percentage']],
            body: [
                ['Total Deviations', stats.total.toString(), '100%'],
                ['Critical', stats.critical.toString(), `${((stats.critical / stats.total) * 100).toFixed(1)}%`],
                ['Major', stats.major.toString(), `${((stats.major / stats.total) * 100).toFixed(1)}%`],
                ['Minor', stats.minor.toString(), `${((stats.minor / stats.total) * 100).toFixed(1)}%`],
                ['Open', stats.open.toString(), `${((stats.open / stats.total) * 100).toFixed(1)}%`],
                ['Under Investigation', stats.investigating.toString(), `${((stats.investigating / stats.total) * 100).toFixed(1)}%`],
                ['Closed', stats.closed.toString(), `${((stats.closed / stats.total) * 100).toFixed(1)}%`],
            ],
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: this.margin, right: this.margin },
        });

        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;

        // Detailed Deviation List
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Deviation Details', this.margin, this.currentY);
        this.currentY += 7;

        const deviationData = deviations.map(dev => [
            dev.deviationNumber,
            dev.title,
            dev.severity,
            dev.status,
            format(new Date(dev.reportedDate), 'yyyy-MM-dd'),
            dev.investigationBy || 'Unassigned',
        ]);

        autoTable(this.doc, {
            startY: this.currentY,
            head: [['Number', 'Title', 'Severity', 'Status', 'Reported', 'Investigator']],
            body: deviationData,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 8 },
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 20 },
                3: { cellWidth: 25 },
                4: { cellWidth: 25 },
                5: { cellWidth: 30 },
            },
        });

        this.addFooter();
    }

    // CAPA Effectiveness Report
    generateCAPAEffectivenessReport(
        capas: CAPA[],
        generatedBy: string
    ): void {
        const header: ReportHeader = {
            title: 'CAPA Effectiveness Report',
            subtitle: 'Corrective and Preventive Actions Analysis',
            documentNumber: `CAPA-RPT-${format(new Date(), 'yyyyMMdd-HHmmss')}`,
            generatedBy,
            generatedAt: new Date(),
        };

        this.addHeader(header);

        // CAPA Statistics
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('CAPA Statistics', this.margin, this.currentY);
        this.currentY += 7;

        const stats = this.calculateCAPAStats(capas);

        autoTable(this.doc, {
            startY: this.currentY,
            head: [['Metric', 'Count', 'Percentage']],
            body: [
                ['Total CAPAs', stats.total.toString(), '100%'],
                ['Corrective Actions', stats.corrective.toString(), `${((stats.corrective / stats.total) * 100).toFixed(1)}%`],
                ['Preventive Actions', stats.preventive.toString(), `${((stats.preventive / stats.total) * 100).toFixed(1)}%`],
                ['Effective', stats.effective.toString(), `${((stats.effective / stats.total) * 100).toFixed(1)}%`],
                ['Not Effective', stats.notEffective.toString(), `${((stats.notEffective / stats.total) * 100).toFixed(1)}%`],
                ['Pending Verification', stats.pending.toString(), `${((stats.pending / stats.total) * 100).toFixed(1)}%`],
            ],
            theme: 'grid',
            headStyles: { fillColor: [16, 185, 129] },
            margin: { left: this.margin, right: this.margin },
        });

        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;

        // Detailed CAPA List
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('CAPA Details', this.margin, this.currentY);
        this.currentY += 7;

        const capaData = capas.map(capa => [
            capa.capaNumber,
            capa.title,
            capa.type,
            capa.status,
            capa.targetDate ? format(new Date(capa.targetDate), 'yyyy-MM-dd') : 'N/A',
            capa.effectivenessCheck?.isEffective !== undefined
                ? (capa.effectivenessCheck.isEffective ? 'Effective' : 'Not Effective')
                : 'Pending',
        ]);

        autoTable(this.doc, {
            startY: this.currentY,
            head: [['Number', 'Title', 'Type', 'Status', 'Target Date', 'Effectiveness']],
            body: capaData,
            theme: 'striped',
            headStyles: { fillColor: [16, 185, 129] },
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 8 },
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 25 },
                3: { cellWidth: 25 },
                4: { cellWidth: 25 },
                5: { cellWidth: 25 },
            },
        });

        this.addFooter();
    }

    // Sample Test Results Report
    generateSampleTestReport(
        sample: Sample,
        generatedBy: string
    ): void {
        const { products } = useMasterDataStore.getState();
        const product = products.find(p => p.id === sample.productId);

        const header: ReportHeader = {
            title: 'Sample Test Results Report',
            subtitle: `${product?.name || 'Unknown Product'} - Batch: ${sample.batchNumber}`,
            documentNumber: sample.sampleNumber,
            generatedBy,
            generatedAt: new Date(),
        };

        this.addHeader(header);

        // Sample Information
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Sample Information', this.margin, this.currentY);
        this.currentY += 7;

        autoTable(this.doc, {
            startY: this.currentY,
            body: [
                ['Sample Number', sample.sampleNumber],
                ['Product', product?.name || 'Unknown'],
                ['Batch Number', sample.batchNumber],
                ['Received Date', format(new Date(sample.receivedDate), 'yyyy-MM-dd')],
                ['Status', sample.status.toUpperCase()],
                ['Tested By', sample.results[0]?.enteredBy || 'Pending'],
            ],
            theme: 'plain',
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 10 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' },
            },
        });

        this.currentY = (this.doc as any).lastAutoTable.finalY + 15;

        // Test Results
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Test Results', this.margin, this.currentY);
        this.currentY += 7;

        if (sample.results && sample.results.length > 0) {
            const testResultData = sample.results.map(testResult => [
                testResult.results?.parameter || 'Unknown',
                testResult.results?.result || 'Pending',
                testResult.results?.unit || '-',
                testResult.results?.specification || '-',
                testResult.status.toUpperCase(),
                testResult.enteredBy || '-',
                testResult.enteredAt ? format(new Date(testResult.enteredAt), 'yyyy-MM-dd') : '-',
            ]);

            autoTable(this.doc, {
                startY: this.currentY,
                head: [['Parameter', 'Result', 'Unit', 'Specification', 'Status', 'Tested By', 'Date']],
                body: testResultData,
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
                margin: { left: this.margin, right: this.margin },
                styles: { fontSize: 8 },
                columnStyles: {
                    0: { cellWidth: 25 },
                    1: { cellWidth: 20 },
                    2: { cellWidth: 15 },
                    3: { cellWidth: 30 },
                    4: { cellWidth: 20 },
                    5: { cellWidth: 25 },
                    6: { cellWidth: 20 },
                    7: { cellWidth: 'auto' },
                },
            });
        }

        this.addFooter();
    }

    // Helper methods
    private getFilterDescription(filters: any): string {
        const parts: string[] = [];
        if (filters.status) parts.push(`Status: ${filters.status}`);
        if (filters.severity) parts.push(`Severity: ${filters.severity}`);
        if (filters.dateRange) {
            parts.push(`Date Range: ${format(filters.dateRange.start, 'yyyy-MM-dd')} to ${format(filters.dateRange.end, 'yyyy-MM-dd')}`);
        }
        return parts.join(' | ');
    }

    private calculateDeviationStats(deviations: Deviation[]) {
        return {
            total: deviations.length,
            critical: deviations.filter(d => d.severity === 'critical').length,
            major: deviations.filter(d => d.severity === 'major').length,
            minor: deviations.filter(d => d.severity === 'minor').length,
            open: deviations.filter(d => d.status === 'open').length,
            investigating: deviations.filter(d => d.status === 'under_investigation').length,
            closed: deviations.filter(d => d.status === 'closed').length,
        };
    }

    private calculateCAPAStats(capas: CAPA[]) {
        return {
            total: capas.length,
            corrective: capas.filter(c => c.type === 'corrective').length,
            preventive: capas.filter(c => c.type === 'preventive').length,
            effective: capas.filter(c => c.effectivenessCheck?.isEffective === true).length,
            notEffective: capas.filter(c => c.effectivenessCheck?.isEffective === false).length,
            pending: capas.filter(c => c.effectivenessCheck?.isEffective === undefined).length,
        };
    }

    // Save the PDF
    save(filename: string): void {
        this.doc.save(filename);
    }

    // Get the PDF as blob
    getBlob(): Blob {
        return this.doc.output('blob');
    }
}

// Export convenience functions
export const generateDeviationReport = (
    deviations: Deviation[],
    generatedBy: string,
    filters?: any
): void => {
    const generator = new ReportGenerator();
    generator.generateDeviationSummaryReport(deviations, generatedBy, filters);
    generator.save(`Deviation_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const generateCAPAReport = (
    capas: CAPA[],
    generatedBy: string
): void => {
    const generator = new ReportGenerator();
    generator.generateCAPAEffectivenessReport(capas, generatedBy);
    generator.save(`CAPA_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const generateSampleReport = (
    sample: Sample,
    generatedBy: string
): void => {
    const generator = new ReportGenerator();
    generator.generateSampleTestReport(sample, generatedBy);
    generator.save(`Sample_Report_${sample.sampleNumber}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export default ReportGenerator;
