import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { StabilityStudy } from '../types/stability';
import { useCompanyConfig } from '../stores/companyConfigStore';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: typeof autoTable;
        lastAutoTable: {
            finalY: number;
        };
    }
}

interface ReportHeader {
    title: string;
    subtitle?: string;
    documentNumber?: string;
    generatedBy: string;
    generatedAt: Date;
}

class StabilityReportGenerator {
    private doc: jsPDF;
    private pageWidth: number;
    private pageHeight: number;
    private margin: number = 15;
    private currentY: number = 15;

    constructor() {
        this.doc = new jsPDF();
        this.pageWidth = this.doc.internal.pageSize.getWidth();
        this.pageHeight = this.doc.internal.pageSize.getHeight();
    }

    private checkPageBreak(requiredSpace: number = 40): void {
        if (this.currentY + requiredSpace > this.pageHeight - 30) {
            this.doc.addPage();
            this.currentY = this.margin;
        }
    }

    private addHeader(header: ReportHeader) {
        const { config } = useCompanyConfig.getState();

        // Helper function to convert hex to RGB
        const hexToRgb = (hex: string): [number, number, number] => {
            const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            return result
                ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
                : [59, 130, 246]; // Default blue
        };

        const bgColor = hexToRgb(config.headerBackgroundColor);
        const textColor = hexToRgb(config.headerTextColor);

        // Company Header Section
        this.doc.setFillColor(...bgColor);
        this.doc.rect(0, 0, this.pageWidth, 35, 'F');

        // Logo
        if (config.logoFile) {
            try {
                this.doc.addImage(config.logoFile, 'PNG', this.margin, 5, 25, 25);
            } catch (e) {
                console.error('Failed to add logo', e);
            }
        }

        // Company Name
        this.doc.setTextColor(...textColor);
        this.doc.setFontSize(16);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(config.companyName, this.pageWidth / 2, 12, { align: 'center' });

        // Company Address
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(config.companyAddress, this.pageWidth / 2, 18, { align: 'center' });
        this.doc.text(`Phone: ${config.companyPhone} | Email: ${config.companyEmail}`, this.pageWidth / 2, 23, { align: 'center' });
        if (config.companyWebsite) {
            this.doc.text(config.companyWebsite, this.pageWidth / 2, 28, { align: 'center' });
        }

        // Report Title
        this.currentY = 45;
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFontSize(18);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(header.title, this.pageWidth / 2, this.currentY, { align: 'center' });

        if (header.subtitle) {
            this.currentY += 7;
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'normal');
            this.doc.text(header.subtitle, this.pageWidth / 2, this.currentY, { align: 'center' });
        }

        // Document Info Box
        this.currentY += 10;
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');

        const infoX = this.pageWidth - this.margin - 60;
        if (header.documentNumber) {
            this.doc.text(`Doc #: ${header.documentNumber}`, infoX, this.currentY);
            this.currentY += 5;
        }
        this.doc.text(`Generated By: ${header.generatedBy}`, infoX, this.currentY);
        this.currentY += 5;
        this.doc.text(`Date: ${format(header.generatedAt, 'yyyy-MM-dd HH:mm')}`, infoX, this.currentY);

        this.currentY += 10;

        // Separator line
        this.doc.setDrawColor(200, 200, 200);
        this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
        this.currentY += 10;
    }

    private addFooter() {
        const { config } = useCompanyConfig.getState();
        const pageCount = this.doc.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);
            this.doc.setFontSize(8);
            this.doc.setTextColor(128, 128, 128);

            // Page number
            this.doc.text(
                `Page ${i} of ${pageCount}`,
                this.pageWidth / 2,
                this.pageHeight - 10,
                { align: 'center' }
            );

            // Confidential notice
            this.doc.text(
                'CONFIDENTIAL - For Internal Use Only',
                this.margin,
                this.pageHeight - 10
            );

            // Company name
            this.doc.text(
                config.companyName,
                this.pageWidth - this.margin,
                this.pageHeight - 10,
                { align: 'right' }
            );
        }
    }

    private addSignatureSection() {
        this.checkPageBreak(60);

        this.currentY += 10;
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Approvals', this.margin, this.currentY);
        this.currentY += 10;

        const signatureWidth = 70;
        const signatureHeight = 25;
        const gap = 10;

        // Prepared By
        this.doc.setFontSize(10);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('Prepared By:', this.margin, this.currentY);
        this.doc.rect(this.margin, this.currentY + 2, signatureWidth, signatureHeight);
        this.doc.setFontSize(8);
        this.doc.text('Signature: _____________________', this.margin + 2, this.currentY + signatureHeight - 8);
        this.doc.text('Date: _____________', this.margin + 2, this.currentY + signatureHeight - 2);

        // Reviewed By
        const reviewX = this.margin + signatureWidth + gap;
        this.doc.setFontSize(10);
        this.doc.text('Reviewed By:', reviewX, this.currentY);
        this.doc.rect(reviewX, this.currentY + 2, signatureWidth, signatureHeight);
        this.doc.setFontSize(8);
        this.doc.text('Signature: _____________________', reviewX + 2, this.currentY + signatureHeight - 8);
        this.doc.text('Date: _____________', reviewX + 2, this.currentY + signatureHeight - 2);

        this.currentY += signatureHeight + 10;

        // Approved By (Manager)
        this.doc.setFontSize(10);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Approved By (QA Manager):', this.margin, this.currentY);
        this.currentY += 2;
        this.doc.rect(this.margin, this.currentY, signatureWidth, signatureHeight);
        this.doc.setFontSize(8);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('Signature: _____________________', this.margin + 2, this.currentY + signatureHeight - 8);
        this.doc.text('Date: _____________', this.margin + 2, this.currentY + signatureHeight - 2);

        this.currentY += signatureHeight + 5;
    }

    // Generate Stability Study Report
    generateStabilityStudyReport(
        study: StabilityStudy,
        generatedBy: string
    ): void {
        const header: ReportHeader = {
            title: 'Stability Study Report',
            subtitle: `${study.productName} - Batch: ${study.batchNumber}`,
            documentNumber: study.studyNumber,
            generatedBy,
            generatedAt: new Date(),
        };

        this.addHeader(header);

        // Study Information
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Study Information', this.margin, this.currentY);
        this.currentY += 7;

        autoTable(this.doc, {
            startY: this.currentY,
            body: [
                ['Study Number', study.studyNumber],
                ['Product Name', study.productName],
                ['Batch Number', study.batchNumber],
                ['Study Type', study.studyType.replace('_', '-').toUpperCase()],
                ['Storage Condition', `${study.storageCondition.temperature} / ${study.storageCondition.humidity || 'N/A'}`],
                ['Start Date', format(new Date(study.startDate), 'yyyy-MM-dd')],
                ['Status', study.status.toUpperCase()],
                ['Created By', study.createdBy],
            ],
            theme: 'plain',
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 10 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' },
            },
        });

        this.currentY = this.doc.lastAutoTable.finalY + 15;

        // Time Points and Test Results
        this.checkPageBreak();
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Stability Test Results', this.margin, this.currentY);
        this.currentY += 7;

        study.timePoints.forEach((timePoint) => {
            this.checkPageBreak(50);

            // Time Point Header
            this.doc.setFontSize(11);
            this.doc.setFont('helvetica', 'bold');
            this.doc.setFillColor(240, 240, 240);
            this.doc.rect(this.margin, this.currentY, this.pageWidth - 2 * this.margin, 8, 'F');
            this.doc.text(
                `Time Point: ${timePoint.timePoint} | Scheduled: ${format(new Date(timePoint.scheduledDate), 'yyyy-MM-dd')} | Status: ${timePoint.status.toUpperCase()}`,
                this.margin + 2,
                this.currentY + 5
            );
            this.currentY += 12;

            if (timePoint.testResults && timePoint.testResults.length > 0) {
                const resultData = timePoint.testResults.map(result => [
                    result.parameter,
                    result.result + ' ' + (result.unit || ''),
                    result.specification,
                    result.status.toUpperCase(),
                    result.testedBy,
                    format(new Date(result.testedDate), 'yyyy-MM-dd'),
                    result.remarks || '-'
                ]);

                autoTable(this.doc, {
                    startY: this.currentY,
                    head: [['Parameter', 'Result', 'Specification', 'Status', 'Tested By', 'Date', 'Remarks']],
                    body: resultData,
                    theme: 'striped',
                    headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
                    margin: { left: this.margin, right: this.margin },
                    styles: { fontSize: 8 },
                    columnStyles: {
                        0: { cellWidth: 25 },
                        1: { cellWidth: 20 },
                        2: { cellWidth: 30 },
                        3: { cellWidth: 18 },
                        4: { cellWidth: 25 },
                        5: { cellWidth: 22 },
                        6: { cellWidth: 'auto' },
                    },
                });

                this.currentY = this.doc.lastAutoTable.finalY + 5;
            } else {
                this.doc.setFontSize(9);
                this.doc.setFont('helvetica', 'italic');
                this.doc.setTextColor(128, 128, 128);
                this.doc.text('No test results recorded for this time point.', this.margin + 5, this.currentY);
                this.doc.setTextColor(0, 0, 0);
                this.currentY += 10;
            }

            if (timePoint.observations) {
                this.doc.setFontSize(9);
                this.doc.setFont('helvetica', 'bold');
                this.doc.text('Observations:', this.margin + 5, this.currentY);
                this.currentY += 5;
                this.doc.setFont('helvetica', 'normal');
                const observations = this.doc.splitTextToSize(timePoint.observations, this.pageWidth - 2 * this.margin - 10);
                this.doc.text(observations, this.margin + 5, this.currentY);
                this.currentY += observations.length * 4 + 5;
            }

            this.currentY += 5;
        });

        // Add signature section
        this.addSignatureSection();

        // Add footer to all pages
        this.addFooter();
    }

    // Save the PDF
    save(filename: string): void {
        this.doc.save(filename);
    }

    // Get the PDF as blob
    getBlob(): Blob {
        return this.doc.output('blob');
    }
}

// Export convenience function
export const generateStabilityReport = (
    study: StabilityStudy,
    generatedBy: string
): void => {
    const generator = new StabilityReportGenerator();
    generator.generateStabilityStudyReport(study, generatedBy);
    generator.save(`Stability_Report_${study.studyNumber}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export default StabilityReportGenerator;
